# status bar
set-option -g status-utf8 on

# Fix OS X clipboard support
set-option -g default-command "reattach-to-user-namespace -l zsh"

# zsh, homie
set-option -g default-shell "/bin/zsh"
set-option -g default-command "/bin/zsh"

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# remap prefix to Control + a
set -g prefix C-a
bind-key C-a last-window

set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg colour244 #base0
set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg colour166 #orange
#set-window-option -g window-status-current-bg default
set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
# clock
set-window-option -g clock-mode-colour green #green

# vim-like motion bindings
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vi-copy mode
bind -t vi-copy v begin-selection
bind -t vi-copy y copy-selection

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Sane scrolling with the mouse
# set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set-window-option -g mode-mouse on
set -g terminal-overrides 'screen*:smcup@:rmcup@'

# If multiple panes exist, Ctrl-a switches to the last one. Otherwise, it switches to the last window.
bind-key C-a if-shell 'test $(tmux list-panes | wc -l) -gt 1' 'last-pane' 'last-window'

# Set ability to capture on start and restore on exit window data when running an application
setw -g alternate-screen on
